[project]
name = "frazer"
version = "0.0.1"
description = "Obtain explanation for sentences in Polish language."
authors = [
    { name = "Adriano Oliveira" }
]
readme = "README.md"
requires-python = ">=3.12,<3.13"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [
    "pytest==8.*",
    "pytest-cov",
]