name: Deploy

on:
  push:
    branches:
        - main
        - cicd

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create Lambda package
        run: |
          python -m pip install --upgrade pip
          make lambda

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name frazer --zip-file fileb://frazer-lambda.zip

      - name: Build frontend
        run: |
          make build-site

      - name: Deploy site
        run: |
          aws s3 --profile=frazer cp site/frazer.html s3://${{ secrets.BUCKET }}/frazer.html --acl public-read