name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  LAMBDA_FUNCTION: frazer

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.8"

      - name: Extract Version
        id: get_version
        run: |
          VERSION=$(uv run --with frazer python -c "import frazer; print(frazer.__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check version exists
        run: |
          git fetch --tags
          TAGS=$(git tag)
          if echo "$TAGS" | grep -q "^v$VERSION$"; then
            echo "Tag v$VERSION exists! Bump the __version__ of the app to proceed with the deploy."
            exit 1
          fi

      - name: Create Lambda package
        run: |
          make lambda

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:  ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION \
            --zip-file fileb://frazer-lambda.zip \
            --no-cli-pager \
            --query 'FunctionArn' --output text
      
          echo "Waiting for Lambda update to complete..."
          aws lambda wait function-updated --function-name $LAMBDA_FUNCTION
      
          # Get the update-function-code status
          STATUS=$(aws lambda get-function --function-name $LAMBDA_FUNCTION --query 'Configuration.LastUpdateStatus' --output text)
      
          if [[ "$STATUS" == "Successful" ]]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed with status: $STATUS"
            exit 1
          fi

      - name: Build webapp
        env: 
          SENTENCE_API_URL: ${{ secrets.SENTENCE_API_URL }}
        run: |
          make build-site

      - name: Deploy site
        run: |
          aws s3 cp site/frazer.html s3://${{ secrets.BUCKET }}/frazer.html --acl public-read

      - name: Create Git Tag
        run: |
          echo "Creating tag v$VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}