name: Check Version Tag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-version-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Extract version from Python file
        id: get_version
        run: |
          pip install -e .
          VERSION=$(python -c "import frazer; print(frazer.__version__)")
          echo "Version found: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if Git tag exists
        run: |
          git fetch --tags
          TAGS=$(git tag)
          echo "Existing tags: $TAGS"
          if echo "$TAGS" | grep -q "^v$VERSION$"; then
            echo "Tag v$VERSION already exists! Bump the __version__ of the app."
            exit 1
          else
            echo "Version $VERSION does not yet have a tag for it."
          fi
        shell: bash
